# Generated by Django 6.0.4 on 2026-04-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_npctemplate'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scenarionpc',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scenario',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10),
        ),
        migrations.AddField(
            model_name='scenarionpc',
            name='display_name',
            field=models.CharField(blank=True, help_text="Override NPC name for this scenario (e.g. 'Zombie #2')", max_length=200),
        ),
        migrations.AddField(
            model_name='scenarionpc',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this NPC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.npctemplate'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Not Started'), ('ACTIVE', 'Ongoing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Done')], default='PLANNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='scenarionpc',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_appearances', to='characters.character'),
        ),
    ]
