# Generated by Django 6.0.4 on 2026-04-26 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characters.character'),
        ),
        migrations.AddField(
            model_name='charactermentaldisorder',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_disorders', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterspell',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterstatuseffect',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_effects', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.item'),
        ),
        migrations.AddField(
            model_name='charactermentaldisorder',
            name='disorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.mentaldisorder'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.skill'),
        ),
        migrations.AddField(
            model_name='characterspell',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.spell'),
        ),
        migrations.AddField(
            model_name='characterstatuseffect',
            name='status_effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.statuseffect'),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapon'),
        ),
        migrations.AlterUniqueTogether(
            name='charactermentaldisorder',
            unique_together={('character', 'disorder')},
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together={('character', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='characterspell',
            unique_together={('character', 'spell')},
        ),
    ]
