# Generated by Django 6.0.4 on 2026-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='badge_color',
            field=models.CharField(choices=[('bg-warning', 'Amber'), ('bg-danger', 'Red'), ('bg-info', 'Blue'), ('bg-secondary', 'Gray'), ('bg-success', 'Green'), ('bg-primary', 'Indigo'), ('bg-dark', 'Dark')], default='bg-info', max_length=20),
        ),
    ]
