# Generated by Django 6.0.4 on 2026-04-27 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_npctemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterstatuseffect',
            options={'ordering': ['-acquired_at']},
        ),
        migrations.AlterModelOptions(
            name='statuseffect',
            options={'ordering': ['effect_type', 'name']},
        ),
        migrations.AddField(
            model_name='characterskill',
            name='needs_update',
            field=models.BooleanField(default=False, help_text='Keeper flag: skill needs update after session'),
        ),
        migrations.AddField(
            model_name='characterstatuseffect',
            name='acquired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='effect_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Status Effect'), ('PHOBIA', 'Phobia'), ('MADNESS', 'Madness'), ('MANIA', 'Mania'), ('DEEP_WOUND', 'Deep Wound')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='game_rules_json',
            field=models.JSONField(blank=True, default=dict, help_text='Custom game rules data'),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='icon_class',
            field=models.CharField(default='bi-shield-exclamation', help_text='Bootstrap icon class for display', max_length=50),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='If true, effect cannot be automatically removed'),
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
